name: 'Create a release'
description: 'Create a release for a tag in your repository'
author: 'easyware.io'
inputs:
  token:
    required: true
    description: 'GitHub token'
  tag_name:
    required: true
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
  release_name:
    required: true
    description: 'The name of the release. For example, `v1.0.1`'
  body:
    required: false
    description: 'Text describing the contents of the tag.'
  body_path:
    required: false
    description: 'Path to file with information about the tag.'
  draft:
    required: false
    description: '`true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`'
  prerelease:
    required: false
    description: '`true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`'
  commitish:
    required: false
    description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit'
  owner:
    required: false
    description: 'Owner of the repository if it is not the current one'
  repo:
    required: false
    description: 'Repository on which to release.  Used only if you want to create the release on another repo'
  make_latest:
    required: false
    description: 'Optional. Possible values are `true`, `false` and `legacy`'
outputs:
  data:
    description: 'The release data'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: tag
  color: orange
